### ISSUE TITLE
how use query with template

### ISSUE THREAD

**Issue by megagoo** [isRuslan/php-template#3]
how use query with template, i try use but dont work 

`
$query_user= "SELECT username,password FROM user";
$user = mysqli_query($sqlconn,$query_user);

while($row = mysqli_fetch_array($user ))
{
    $rows[] = $row;
}

$template->assign('items', array(
print_r($rows);
));
`

**Comment by PedroBlanco** [comment]
First of all, if you are trying to print each pair of 'username' and 'password', the last 3 lines should be

```php
$template->assign('items', $rows);
```

...because $rows is already an array (or should be).

Just in case you didn't include the rest of your code, after assigning '$rows' to 'items' in $template, you have to tell $template to show (parse), like:
```php
$template->parse('my_template.html');
```

The content of 'my_template.html' should include something like

```html
<table>
    <tr><th>User</th><th>Password</th></tr>
    {loop items}
        <tr><td>{username}</td><td>{password}</td></tr>
    {end loop}
</table>
```

...assuming your 'mysqli_fetch_array' returns an associative array with 'username' and 'password' keys (it is the default option, I think).

I hope it helps.

**Comment by megagoo** [comment]
thanks :)
